version: '3.9'

services:
  neo4j:
    image: neo4j:5.17.0-enterprise
    volumes:
      - graph_data:/neo4j/data:/data
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD}
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    ports:
      - 7474:7474
      - 7687:7687
  graph_kb_service:
    build: graph_kb_service
    volumes:
      - ./graph_kb_service:/usr/src/graph_kb_service
    env_file:
      - ./graph_kb_service/.env
    depends_on:
      - neo4j
      - relation_extraction_model
    ports:
      - 7777:8000
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload --log-config /usr/src/graph_kb_service/uvicorn_logging.conf"
  graph_rag_service:
    build: graph_rag_service
    volumes:
      - ./graph_rag_service:/usr/src/graph_rag_service
    env_file:
      - ./graph_rag_service/.env
    depends_on:
      - neo4j
    ports:
      - 7780:8000
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload --log-config /usr/src/graph_rag_service/uvicorn_logging.conf"
  vaults_service_postgres:
    image: postgres:16.1-bullseye
    volumes:
      - vaults_service_postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${VAULTS_SERVICE_POSTGRES_DB_NAME}
      - POSTGRES_USER=${VAULTS_SERVICE_POSTGRES_DB_USER}
      - POSTGRES_PASSWORD=${VAULTS_SERVICE_POSTGRES_DB_PASSWORD}
    ports:
      - ${VAULTS_SERVICE_POSTGRES_DB_CONTAINER_PORT}:5432
  vaults_service:
    build: vaults_service
    volumes:
      - ./vaults_service:/usr/src/vaults_service
    env_file:
      - ./vaults_service/.env
    ports:
      - 7778:8000
    depends_on:
      - vaults_service_postgres
      - graph_kb_service
    command: >
      sh -c "alembic upgrade head && 
      uvicorn main:app --host 0.0.0.0 --port 8000 --reload --log-config /usr/src/vaults_service/uvicorn_logging.conf"

volumes:
  graph_data:
  vaults_service_postgres_data:
