version: '3.9'

services:
  embeddings_model:
    build: embedding-model-service
    volumes:
      - ./embedding-model-service:/usr/src/embedding-model-service
    env_file:
      - .env
    ports:
      - ${EMBEDDINGS_MODEL_PORT}:8000
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
      
  qdrant:
    image: qdrant/qdrant:v1.9.0
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - ./qdrant_storage:/qdrant/storage

  vector_kb_service:
    build: vector_kb_service
    volumes:
      - ./vector_kb_service:/usr/src/vector_kb_service
    env_file:
      - .env
    ports:
      - ${VECTOR_KB_SERVICE_PORT}:8000
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

  vector_rag_service:
    build: vector_rag_service
    volumes:
      - ./vector_rag_service:/usr/src/vector_rag_service
    env_file:
      - .env
    ports:
      - ${VECTOR_RAG_SERVICE_PORT}:8000
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

