services:
  embeddings_model:
    build: embedding-service
    restart: unless-stopped 
    ports:
      - 8004:8000
    deploy:
      resources:
          reservations:
              devices:
                  - driver: nvidia
                    device_ids: ['1']
                    capabilities: [ gpu ]
    volumes:
      - ./embedding-service:/usr/src/embedding-service
      - /home/ontollm/.cache/huggingface/hub:/home/papper_user/.cache/huggingface/hub
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"