version: '3.9'

services:
  neo4j:
    image: neo4j:5.17.0-community
    volumes:
      - graph_data:/neo4j/data:/data
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD}
    ports:
      - 7474:7474
      - 7687:7687
  graph_vault:
    build: graph_vault
    volumes:
      - ./graph_vault:/usr/src/graph_vault
    env_file:
      - .env
    depends_on:
      - neo4j
    ports:
      - ${HOST_PORT}:8000
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

volumes:
  graph_data:
