version: '3.9'

services:
  neo4j:
    image: neo4j:5.17.0-enterprise
    volumes:
      - graph_data:/neo4j/data:/data
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD}
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    ports:
      - 7474:7474
      - 7687:7687
  graph_vault:
    build: graph_vault
    volumes:
      - ./graph_vault:/usr/src/graph_vault
    env_file:
      - ./graph_vault/.env
    depends_on:
      - neo4j
    ports:
      - 7777:8000
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload --log-config /usr/src/graph_vault/uvicorn_logging.conf"
  relation_extraction_model:
    build: relation_extraction_model
    volumes:
      - ./relation_extraction_model:/usr/src/relation_extraction_model
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload --log-config /usr/src/relation_extraction_model/uvicorn_logging.conf"
  documents_service_postgres:
    image: postgres:16.1-bullseye
    volumes:
      - documents_service_postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DOCUMENTS_SERVICE_POSTGRES_DB_NAME}
      - POSTGRES_USER=${DOCUMENTS_SERVICE_POSTGRES_DB_USER}
      - POSTGRES_PASSWORD=${DOCUMENTS_SERVICE_POSTGRES_DB_PASSWORD}
    ports:
      - ${DOCUMENTS_SERVICE_POSTGRES_DB_CONTAINER_PORT}:5432
  documents_service:
    build: documents_service
    volumes:
      - ./documents_service:/usr/src/documents_service
    env_file:
      - ./documents_service/.env
    ports:
      - 7778:8000
    depends_on:
      - documents_service_postgres
    command: > 
      sh -c "alembic upgrade head && 
      uvicorn main:app --host 0.0.0.0 --port 8000 --reload --log-config /usr/src/documents_service/uvicorn_logging.conf"

volumes:
  graph_data:
  documents_service_postgres_data: