version: '3.9'

services:
  neo4j:
    image: neo4j:5.17.0-enterprise
    volumes:
      - graph_data:/neo4j/data:/data
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD}
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
    ports:
      - 7474:7474
      - 7687:7687
  graph_vault:
    build: graph_vault
    volumes:
      - ./graph_vault:/usr/src/graph_vault
    env_file:
      - .env
    depends_on:
      - neo4j
    ports:
      - 7777:8000
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload --log-config /usr/src/graph_vault/uvicorn_logging.conf"
  seq2seq:
    build: seq2seq
    volumes:
      - ./seq2seq:/usr/src/seq2seq
    env_file:
      - .env
    ports:
      - 7778:8000
    command: >
      sh -c "uvicorn main:app --host 0.0.0.0 --port 8000 --reload --log-config /usr/src/seq2seq/uvicorn_logging.conf"

volumes:
  graph_data: